### ISSUE TITLE
Release a version compatible with template-haskell-2.15

### ISSUE THREAD

**Issue by DanBurton** [lexi-lambda/freer-simple#29]
Kindly do a hackage revision, or release a new version that allows for `template-haskell-2.15`.

It is currently constrained to `template-haskell < 2.15`, but it seems to work fine.

I was able to reproduce a successful build & test locally like so:

```bash
stack unpack freer-simple-1.2.1.0 && cd freer-simple-1.2.1.0
edit stack.yaml # add the following stack.yaml
edit freer-simple.cabal  # relax the constraint on template-haskell
stack build --test --bench --no-run-benchmarks --fast
```

```yaml
# stack.yaml
resolver: nightly-2019-09-29
extra-deps:
  - extensible-effects-5.0.0.1@sha256:2ed0bee04c8bf334358147da6d92ff31e9fbbefceb75ef3e408a0d858aec0cc6,9013
```
